name: structs_ffi
version: 0.0.1
description: >-
  A super simple example of calling C code from Dart with FFI using structs
author: Matt Sullivan <mattsullivan@google.com>
environment:
  sdk: '>=2.12.0-259.12.beta <3.0.0'
dependencies:
  ffi: ^1.0.0
  path: ^1.8.0

dev_dependencies:
  test: ^1.16.0
  test_utils:
    path: ../test_utils
