name: cli_app
description: >-
  A command line application that can be compiled to native code using
  dart compile exe.

# This example isn't intended for publishing on pub.dev.
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  args: ^2.5.0
  build_cli_annotations: ^2.1.0
  github: ^9.24.0
  intl: ^0.20.0

dev_dependencies:
  build_cli: ^2.2.3
  build_runner: ^2.4.13
  lints: ^5.0.0
  test: ^1.25.8

executables:
  github_activity: github_activity
