name: cli_app
description: >-
  A command line application that can be compiled to native code using
  dart compile exe.

# This example isn't intended for publishing on pub.dev.
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  args: ^2.7.0
  build_cli_annotations: ^2.1.1
  github: ^9.25.0
  intl: ^0.20.2

dev_dependencies:
  build_cli: ^2.2.8
  build_runner: ^2.10.3
  lints: ^6.0.0
  test: ^1.27.0

executables:
  github_activity: github_activity
