name: primitives_ffi
description: A super simple example of calling C code from Dart with FFI

# This example isn't intended for publishing on pub.dev.
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  ffi: ^2.1.3
  path: ^1.9.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
  # test_utils depends on code elsewhere in the samples repository.
  # You can reference it for useful cross-platform testing functionality
  # or remove it if you want to use this example standalone.
  test_utils:
    path: ../test_utils
