name: parameters
description: Function parameters and super initalizers examples
version: 1.0.0

publish_to: none

environment:
  sdk: '>=2.17.0-182.1.beta <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
