name: constraint_solver
description: A general-purpose backtracking constraint satisfaction algorithm.
version: 1.0.0
repository: https://github.com/dart-lang/samples/tree/main/package_constraint_solver

environment:
  sdk: ^3.0.0

dependencies:
  path: ^1.8.3

dev_dependencies:
  checks: ^0.2.0
  lints: ^2.1.0
  intl: ^0.18.0
  test: ^1.24.0
