name: constraint_solver
description: A general-purpose backtracking constraint satisfaction algorithm.
repository: https://github.com/dart-lang/samples/tree/main/package_constraint_solver
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  path: ^1.9.0

dev_dependencies:
  checks: ^0.3.0
  lints: ^5.0.0
  intl: ^0.20.0
  test: ^1.25.8
