name: constraint_solver
description: A general-purpose backtracking constraint satisfaction algorithm.
repository: https://github.com/dart-lang/samples/tree/main/package_constraint_solver
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  path: ^1.9.1

dev_dependencies:
  checks: ^0.3.1
  lints: ^6.0.0
  intl: ^0.20.2
  test: ^1.27.0
