name: container_server_example
publish_to: none # not intended for publication to pub.dev

environment:
  sdk: ^3.10.0

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_static: ^1.1.3

dev_dependencies:
  http: ^1.6.0
  lints: ^6.0.0
  test: ^1.27.0
  test_process: ^2.1.1
