name: cloud_run_google_apis
publish_to: none # not intended for publication to pub.dev

environment:
  sdk: ^3.0.0

dependencies:
  google_cloud: ^0.2.0
  googleapis: ^11.2.0
  googleapis_auth: ^1.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0

dev_dependencies:
  dart_flutter_team_lints: ^1.0.0
