name: enhanced_enums
description: Samples that demonstrates the enhanced enums syntax

# This example isn't intended for publishing on pub.dev.
publish_to: none

environment:
  sdk: '>=2.17.0-182.1.beta <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
