name: enhanced_enums
description: Samples that demonstrates the enhanced enums syntax

# This example isn't intended for publishing on pub.dev.
publish_to: none

environment:
  sdk: ^3.7.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
