name: calculate_lix
description: A command-line application demonstrating use of null safety.
version: 1.3.0

# This example isn't intended for publishing on pub.dev.
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  collection: ^1.19.0

dev_dependencies:
  lints: ^5.0.0
