name: calculate_lix
description: A command-line application demonstrating use of null safety.
version: 1.1.1

environment:
  sdk: '>=2.10.0-56.0.dev <3.0.0'

dependencies:
  collection: '>=1.15.0-nullsafety.3'
